/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */

import {
    Static,
    Type
} from "@sinclair/typebox";

export type T = Static<typeof T>;
export const T = Type.Object(
  {
    items: Type.Optional(
      Type.Array(
        Type.Object({
          costperunit: Type.Optional(Type.Number()),
          id: Type.Optional(Type.String({ format: "uuid" })),
          sort_id: Type.Optional(Type.Number()),
          filename: Type.Optional(Type.String()),
          material_type_id: Type.Optional(Type.String({ format: "uuid" })),
          fit_id: Type.Optional(Type.String({ format: "uuid" })),
          name: Type.Optional(Type.String()),
          description: Type.Optional(Type.String()),
        })
      )
    ),
    total: Type.Optional(Type.Number()),
    page: Type.Optional(Type.Number()),
    per_page: Type.Optional(Type.Number()),
  },
  { $id: "T" }
);
