/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */

import {
    Static,
    Type
} from "@sinclair/typebox";

export type T = Static<typeof T>;
export const T = Type.Object(
  {
    page: Type.Optional(Type.Number({ minimum: 1, default: 1 })),
    per_page: Type.Optional(
      Type.Number({ minimum: 0, maximum: 50, default: 25 })
    ),
  },
  { $id: "T" }
);
